spring:
  datasource:
    url:  jdbc:h2:~/chat-test
    username: sa
    password:

  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        show_sql: true
