spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/chat-prac
    username: postgres
    password: asdf1020@@
  data:
    mongodb:
      host: localhost
      port: 27017
      database: chat

  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: validate
    defer-datasource-initialization: true
    properties:
      hibernate:
        show_sql: true